Users/random workings/website setup (#5)
* Index, 404, and NoJekyll Files Added

* Fix for Build Error
error CS0234: The type or namespace name 'Shared' does not exist in the namespace 'RWPagesSite' (are you missing an assembly reference?) [/home/runner/work/RandomWorkings.github.io/RandomWorkings.github.io/RandomWorkings.github.io.csproj]

* Fixing Error
Error CS0246: The type or namespace name 'BlazorOnGitHubPages' could not be found (are you missing a using directive or an assembly reference?)