Fixing Error Error CS0246: The type or namespace name 'BlazorOnGitHubPages' could not be found (are you missing a using directive or an assembly reference?)