Users/random workings/website setup (#4)
* Index, 404, and NoJekyll Files Added

* Fix for Build Error
error CS0234: The type or namespace name 'Shared' does not exist in the namespace 'RWPagesSite' (are you missing an assembly reference?) [/home/runner/work/RandomWorkings.github.io/RandomWorkings.github.io/RandomWorkings.github.io.csproj]